<script setup lang="ts">
const route = useRoute();
const localePath = useLocalePath()
const { locale, setLocale, t } = useI18n()
const isNavBarOpen: Ref<boolean> = ref(false);
const navLinks = DataProvider.GetNavBarLinks(t);

const languages: Ref<string[]> = ref([
  "de",
  "en",
]);
const currentLanguage: Ref<string> = ref(locale);

function changeLanguage(lang: string) {
  setLocale(lang);

  setTimeout(() => {
    window.location.reload();
    console.log("Language changed to: " + lang);
  }, 200);
}

function toggleNavBar() {
  isNavBarOpen.value = !isNavBarOpen.value;
}

function getNavBarClass(link: string) {
  const isHomeRoute = route.path === '/' || languages.value.some((lang: string) => route.path === `/${lang}`);

  if (link === '/') {
    // Consider the home route as active for both '/' and language-specific routes like '/de' or '/en'
    return isHomeRoute ? 'navbar-btn-active' : 'navbar-btn';
  }

  return route.path.includes(link) ? 'navbar-btn-active' : 'navbar-btn';
}

const navBarClass = computed(() => isNavBarOpen.value ? 'flex' : 'hidden lg:block');
const navBarIcon = computed(() => isNavBarOpen.value ? 'times' : 'bars');
</script>

<template>
  <nav class="w-full sm:fixed z-40 bg-ownPrimary text-white sm:px-8 shadow-md shadow-gray-800">
    <div class="flex flex-col sm:flex-row justify-between items-center container py-2 lg:py-4 mx-auto">
      <p class="inline text-3xl font-bold text-white my-4 sm:my-0 text-shadow-pop-tr">
        <NuxtLink :to="localePath('/')" class="text-white">
          {{ $t('myName') }}
        </NuxtLink>
      </p>

      <div class="flex items-center gap-8">
        <div :class="navBarClass" class="navbar-content flex-col lg:flex-row">
          <NuxtLink v-for="navLink in navLinks" :to="localePath(navLink[1])" :class="getNavBarClass(navLink[1])"
            class="my-2 lg:my-0 mx-2 px-4 py-2 rounded-md">
            {{ navLink[0] }}
          </NuxtLink>

          <select v-model="currentLanguage" @change="changeLanguage(currentLanguage)"
            class="w-20 inline px-4 py-2 rounded-md navbar-btn-active" :aria-label="$t('mainLayout.languageAriaLabel')">
            <option v-for="language in languages" :key="language" :value="language">
              {{ language.toUpperCase() }}
            </option>
          </select>
        </div>

        <button @click="toggleNavBar" class="block lg:hidden navbar-btn px-4 p-2 rounded-md">
          <fa-icon :icon="navBarIcon" class="text-[1.75rem] sm:text-[2rem]" />
        </button>
      </div>
    </div>
  </nav>
</template>

<style scoped>
.text-shadow-pop-tr {
  -webkit-animation: text-shadow-pop-tr 0.6s both;
  animation: text-shadow-pop-tr 0.6s both;
}

/* ----------------------------------------------
 * Generated by Animista on 2024-8-18 13:50:26
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-shadow-pop-tr
 * ----------------------------------------
 */
@-webkit-keyframes text-shadow-pop-tr {
  0% {
    text-shadow: 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555;
    -webkit-transform: translateX(0) translateY(0);
    transform: translateX(0) translateY(0);
  }

  100% {
    text-shadow: 1px -1px #555555, 2px -2px #555555, 3px -3px #555555, 4px -4px #555555, 5px -5px #555555, 6px -6px #555555, 7px -7px #555555, 8px -8px #555555;
    -webkit-transform: translateX(-8px) translateY(8px);
    transform: translateX(-8px) translateY(8px);
  }
}

@keyframes text-shadow-pop-tr {
  0% {
    text-shadow: 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555;
    -webkit-transform: translateX(0) translateY(0);
    transform: translateX(0) translateY(0);
  }

  100% {
    text-shadow: 1px -1px #555555, 2px -2px #555555, 3px -3px #555555, 4px -4px #555555, 5px -5px #555555, 6px -6px #555555, 7px -7px #555555, 8px -8px #555555;
    -webkit-transform: translateX(-8px) translateY(8px);
    transform: translateX(-8px) translateY(8px);
  }
}
</style>